spring:
  application:
    name: ecommerce
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    url: jdbc:postgresql://localhost:5432/sample
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver
server:
  port: ${SERVER_PORT:9192}
  servlet:
    context-path: /fullstack
  http2.enabled: false
logging:
  level:
    root: INFO
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: ["health","beans","metrics"] #"*" #/health